### ISSUE TITLE
In Docker on Mac spawn sudo ENOENT

### ISSUE THREAD

**Issue by jtwebman** [davidmarkclements/0x#101]
When I try running 0x on a node.js service inside docker I run into issues.

Command: `0x server`
Error:
```
events.js:183
     throw er; // Unhandled 'error' event
      ^

Error: spawn sudo ENOENT
   at _errnoException (util.js:1024:11)
   at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
   at onErrorNT (internal/child_process.js:372:16)
   at _combinedTickCallback (internal/process/next_tick.js:138:11)
   at process._tickCallback (internal/process/next_tick.js:180:9)
   at Function.Module.runMain (module.js:678:11)
   at startup (bootstrap_node.js:187:16)
   at bootstrap_node.js:608:3
```

Am I missing a package. Do I need to build my container differently?

**Comment by davidmarkclements** [comment]
You have to build the container with `perf` compiled into the kernel and run it in privledged mode (https://github.com/davidmarkclements/0x/blob/master/readme.md#docker). Alternatively in the latest 0x you can use the `--v8-prof-only` flag to generate stacks from v8 prof data (requires node 8.9.4 or above).

**Comment by davidmarkclements** [comment]
Closing for now - feel free to reopen if you have further questions
