### ISSUE TITLE
TypeError: Cannot destructure property `fn` of 'undefined' or 'null'

### ISSUE THREAD

**Issue by sudhanshugaur4** [davidmarkclements/0x#117]
/opt/bitnami/nodejs/lib/node_modules/0x/platform/v8.js:99
        const { fn, file } = lastOptimizedFrame
                ^
TypeError: Cannot destructure property `fn` of 'undefined' or 'null'.
    at DestroyableTransform.through [as _transform] (/opt/bitnami/nodejs/lib/node_modules/0x/platform/v8.js:99:30)
    at DestroyableTransform.Transform._read (/opt/bitnami/nodejs/lib/node_modules/0x/node_modules/readable-stream/li
b/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/opt/bitnami/nodejs/lib/node_modules/0x/node_modules/readable-stream/l
ib/_stream_transform.js:172:83)
    at doWrite (/opt/bitnami/nodejs/lib/node_modules/0x/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/opt/bitnami/nodejs/lib/node_modules/0x/node_modules/readable-stream/lib/_stream_writable.js:4
17:5)
    at DestroyableTransform.Writable.write (/opt/bitnami/nodejs/lib/node_modules/0x/node_modules/readable-stream/lib
/_stream_writable.js:334:11)
    at DestroyableTransform.ondata (/opt/bitnami/nodejs/lib/node_modules/0x/node_modules/readable-stream/lib/_stream
_readable.js:619:20)
    at DestroyableTransform.emit (events.js:180:13)
    at addChunk (/opt/bitnami/nodejs/lib/node_modules/0x/node_modules/readable-stream/lib/_stream_readable.js:291:12
)
    at readableAddChunk (/opt/bitnami/nodejs/lib/node_modules/0x/node_modules/readable-stream/lib/_stream_readable.j
s:278:11)

**Comment by davidmarkclements** [comment]
@sudhanshugaur4 does this happen every time ?

**Comment by davidmarkclements** [comment]
fixed in v4.0.8
