### ISSUE TITLE
0x not working with Mongoose package whereas Forever is working perfectly fine.

### ISSUE THREAD

**Issue by sudhanshugaur4** [davidmarkclements/0x#118]
I don't know why this is happening but previously i was using **Forever** module with the command `forever start app.js` to run my node.js app but now as i am using 0x the command i wrote is `0x app.js`, now in logs bellow error is printing

```
{ MongoError: failed to connect to server [XX.XXX.X.X:27017] on first connect [MongoError: connection 0 to XX.XXX.X.X:27017 timed out]
    at Pool.<anonymous> (/home/projects/kj_app/node_modules/mongodb-core/lib/topologies/server.js:336:35)
    at Pool.emit (events.js:180:13)
    at Connection.<anonymous> (/home/projects/kj_app/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at Object.onceWrapper (events.js:272:13)
    at Connection.emit (events.js:180:13)
    at Socket.<anonymous> (/home/projects/kj_app/node_modules/mongodb-core/lib/connection/connection.js:197:10)
    at Object.onceWrapper (events.js:272:13)
    at Socket.emit (events.js:180:13)
    at Socket._onTimeout (net.js:393:8)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
  name: 'MongoError',
```
But the thing is when using **Forever** i am not getting this error and everything is working perfectly fine.

**Comment by davidmarkclements** [comment]
What if you directly with node?

**Comment by sudhanshugaur4** [comment]
Yes it is working perfectly fine for both `node app.js` and for `forever start app.js`

**Comment by sudhanshugaur4** [comment]
Also when i exit the profiling by pressing `Ctrl+C` then i get below error but `flamegraph.html` get successfully created.

```
🔥  Process exited, generating flamegraphevalmachine.<anonymous>:2784
  printErr(str);
  ^
ReferenceError: printErr is not defined
    at TickProcessor.printError (evalmachine.<anonymous>:2784:3)
    at TickProcessor.LogReader.processLog_ (evalmachine.<anonymous>:2536:12)
    at TickProcessor.LogReader.processLogLine (evalmachine.<anonymous>:2419:10)
    at TickProcessor.processLogFile (evalmachine.<anonymous>:2812:10)
    at evalmachine.<anonymous>:3994:15
    at internal/v8_prof_processor.js:41:28
    at NativeModule.compile (bootstrap_node.js:654:7)
    at Function.NativeModule.require (bootstrap_node.js:599:18)
    at startup (bootstrap_node.js:140:20)
    at bootstrap_node.js:666:3
🔥  Flamegraph generated in
file:///home/projects/app/10182.0x/flamegraph.html
```

**Comment by mcollina** [comment]
@sudhanshugaur4 which version of Node.js are you using?
Can you please upload an example that exhibit this behavior?

**Comment by davidmarkclements** [comment]
Yeah that second error is definitely node version related

**Comment by sudhanshugaur4** [comment]
`Node` version is `v9.8.0`.

**Comment by davidmarkclements** [comment]
Ok so that second error is a bug in that
version - bear in mind the 9 branch is
experimental - only even numbers (6,8) are considered production ready

Try a different version of node

**Comment by sudhanshugaur4** [comment]
Ok Let me try any Nodejs 8.X.X version, also `Even numbers` you mean this only for NodeJs or for all other `npm packages` also, never heard about it.

**Comment by davidmarkclements** [comment]
Only Node, odd numbers are "current" which in this context means new features lands on this line, and stay there for at least two weeks before they are backported. Odd numbers and then disappear after a new even major – so when Node 10 is released, the Node 9 line will disappear
see https://github.com/nodejs/Release

**Comment by sudhanshugaur4** [comment]
Hii actually I have two version of node installed on my system one is local and second is bitnami's version provided by default, Can you please tell me how can I pass node version in this command `sudo 0x app.js`.
