### ISSUE TITLE
Error: Cannot find perf on your system!

### ISSUE THREAD

**Issue by binarykitchen** [davidmarkclements/0x#16]
```
$ 0x node ./src/server                                                                                  staging 
/usr/lib/node_modules/0x/index.js:343
  if (!path) { throw Error('Cannot find ' + bin + ' on your system!') }
               ^

Error: Cannot find perf on your system!
    at Error (native)
    at pathTo (/usr/lib/node_modules/0x/index.js:343:22)
    at linux (/usr/lib/node_modules/0x/index.js:144:14)
    at /usr/lib/node_modules/0x/index.js:20:16
    at ChildProcess.<anonymous> (/usr/lib/node_modules/0x/index.js:362:23)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12
```

this on Ubuntu 15.10 ... what do to?

**Comment by yoshuawuyts** [comment]
Have you tried `sudo apt-get install perf`?

**Comment by binarykitchen** [comment]
ah, works now. maybe you want to add this requirement to the readme?

**Comment by davidmarkclements** [comment]
requirement added - thanks for the feedback :grin:
