### ISSUE TITLE
bug: cannot recover from async sudo check

### ISSUE THREAD

**Issue by eljefedelrodeodeljefe** [davidmarkclements/0x#20]
Always when I'll run the program and I will be prompted for sudo auth, the `child_process` throws. potentially we would need to save state and recover

```console
internal/child_process.js:274
  var err = this._handle.spawn(options);
                         ^

TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:274:26)
    at exports.spawn (child_process.js:367:9)
    at sun (/Users/jefe/repos/0x/index.js:157:10)
    at ChildProcess.<anonymous> (/Users/jefe/repos/0x/index.js:88:33)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

**Comment by davidmarkclements** [comment]
Is this before or after your refactor, or both?

**Comment by davidmarkclements** [comment]
Do you mean if pw is wrong? We just need to check exit code

**Comment by eljefedelrodeodeljefe** [comment]
Was in before already and stayed https://youtu.be/9yUE2CaH_k8 . I think this is a little more complicated, because my guess it that any of the `child_process` sockets times out waiting for the users input. Should be fixable though. When you repeat the above step you are sudo and everything works fine.

**Comment by eljefedelrodeodeljefe** [comment]
:+1:
