### ISSUE TITLE
How to run jest with 0x?

### ISSUE THREAD

**Issue by cmdcolin** [davidmarkclements/0x#217]
Hi there,

I tried using just `0x node_modules/.bin/jest` but it gives

```
% 0x node_modules/.bin/jest
🔥  ProfilingError: write EPIPE
    at ChildProcess.target._send (internal/child_process.js:806:20)
    at ChildProcess.target.send (internal/child_process.js:676:19)
    at ChildProcessWorker.send (/home/cdiesh/src/jbrowse-components/node_modules/jest-worker/build/workers/ChildProcessWorker.js:286:17)
    at WorkerPool.send (/home/cdiesh/src/jbrowse-components/node_modules/jest-worker/build/WorkerPool.js:32:34)
    at Farm._process (/home/cdiesh/src/jbrowse-components/node_modules/jest-worker/build/Farm.js:129:10)
    at Farm._enqueue (/home/cdiesh/src/jbrowse-components/node_modules/jest-worker/build/Farm.js:152:10)
    at Farm._push (/home/cdiesh/src/jbrowse-components/node_modules/jest-worker/build/Farm.js:159:12)
    at /home/cdiesh/src/jbrowse-components/node_modules/jest-worker/build/Farm.js:90:14
    at new Promise (<anonymous>)
    at Farm.doWork (/home/cdiesh/src/jbrowse-components/node_modules/jest-worker/build/Farm.js:56:12)
Target subprocess error, code: 1
🔥  Flamegraph generated in
file:///home/cdiesh/src/jbrowse-components/23267.0x/flamegraph.html
```

**Comment by cmdcolin** [comment]
I've had luck with using 0x node_modules/.bin/jest specific_file.test.js instead of without any params

**Comment by davidmarkclements** [comment]
yeah this looks like a Jest specific thing, closing as you've found a work around

**Comment by joscha** [comment]
When I use `0x` to profile jest tests it seems like I only get the graph for the jest execution itself, not for the tests running in it. I am using `--runInBand`, a `testEnvironment: "node"` and a single test file that is executed, so theoretically 0x should be able to pick up the executed test case.

**Comment by janeklb** [comment]
FWIW here's what works for me (`node` 16.15.0, `0x` 5.4.1, `jest` 28.1.3):

```
0x -- node ./node_modules/jest-cli/bin/jest.js --runInBand --config <path-to-my-jest.config.js>
```

**Comment by netroy** [comment]
Update for anyone using jest 29+, You can run profile your tests with:
```
0x ./node_modules/jest/bin/jest.js --no-coverage --runInBand
```

`node_modules/.bin/jest` is a shell script now, and cannot be used with 0x.

**Comment by black-snow** [comment]
When I try `npx 0x ./node_modules/jest/bin/jest.js --ci --silent -i` all test suites fail with:

```
FAIL whatever.spec.ts
  ● Test suite failed to run

    Jest worker encountered 4 child process exceptions, exceeding retry limit

      at ChildProcessWorker.initialize (node_modules/jest-worker/build/workers/ChildProcessWorker.js:181:21)

node:net:441
      throw errnoException(err, 'open');
      ^

Error: open EEXIST
    at new Socket (node:net:441:13)
    at Object.<anonymous> (/root/.npm/_npx/157372ca833166ed/node_modules/0x/lib/preload/redir-stdout.js:11:18)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at internalRequire (node:internal/modules/cjs/loader:174:19)
    at Module._preloadModules (node:internal/modules/cjs/loader:1433:5)
    at loadPreloadModules (node:internal/process/pre_execution:611:5)
    at setupUserModules (node:internal/process/pre_execution:130:3) {
  errno: -17,
  code: 'EEXIST',
  syscall: 'open'
}

Node.js v18.18.2
```

**Comment by davidminor** [comment]
> When I try `npx 0x ./node_modules/jest/bin/jest.js --ci --silent -i` all test suites fail with:
> 
> ```
> FAIL whatever.spec.ts
>   ● Test suite failed to run
> 
>     Jest worker encountered 4 child process exceptions, exceeding retry limit
> 
>       at ChildProcessWorker.initialize (node_modules/jest-worker/build/workers/ChildProcessWorker.js:181:21)
> 
> node:net:441
>       throw errnoException(err, 'open');
>       ^
> 
> Error: open EEXIST
>     at new Socket (node:net:441:13)
>     at Object.<anonymous> (/root/.npm/_npx/157372ca833166ed/node_modules/0x/lib/preload/redir-stdout.js:11:18)
>     at Module._compile (node:internal/modules/cjs/loader:1256:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
>     at Module.load (node:internal/modules/cjs/loader:1119:32)
>     at Module._load (node:internal/modules/cjs/loader:960:12)
>     at internalRequire (node:internal/modules/cjs/loader:174:19)
>     at Module._preloadModules (node:internal/modules/cjs/loader:1433:5)
>     at loadPreloadModules (node:internal/process/pre_execution:611:5)
>     at setupUserModules (node:internal/process/pre_execution:130:3) {
>   errno: -17,
>   code: 'EEXIST',
>   syscall: 'open'
> }
> 
> Node.js v18.18.2
> ```
> 
> [@davidmarkclements](https://github.com/davidmarkclements) any quick ideas? :)

I was having this issue and adding `--runInBand --workerThreads` seems to do the trick
