### ISSUE TITLE
Error: Cannot find perf on your system!

### ISSUE THREAD

**Issue by jeromecovington** [davidmarkclements/0x#23]
On Ubuntu 15.10:
```
> ./node_modules/.bin/0x node benchmark/single.js
/home/jtkc/autopilot-vogue-runway/node_modules/0x/index.js:371
  if (!path) { throw Error('Cannot find ' + bin + ' on your system!') }
               ^

Error: Cannot find perf on your system!
    at Error (native)
    at pathTo (/home/jtkc/autopilot-vogue-runway/node_modules/0x/index.js:371:22)
    at linux (/home/jtkc/autopilot-vogue-runway/node_modules/0x/index.js:159:14)
    at /home/jtkc/autopilot-vogue-runway/node_modules/0x/index.js:21:16
    at ChildProcess.<anonymous> (/home/jtkc/autopilot-vogue-runway/node_modules/0x/index.js:391:5)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

**Comment by jeromecovington** [comment]
Ha! Just read the README. Sorry guys.

Linux - requires perf

**Comment by eljefedelrodeodeljefe** [comment]
Yeah, I find Ubuntu annoying over not including linux tools automatically. But they probably had their reasons.
