### ISSUE TITLE
`Unable to find map file!` when running against Express server

### ISSUE THREAD

**Issue by Limess** [davidmarkclements/0x#33]
I get the following output and a hanging clockface icon when I try to use `0x` on OSX 10.10.5. 
I'm running `0x` on an express application using node v4.4.4.

When I run 
`DEBUG=0x* 0x -p --trace-info node server.js`
Upon sending a `SIGINT` (`ctrl+c`) to `0x` I get the following message: 
```
0x Caught SIGINT, generating flamegraph +0ms
Unable to find map file!
  0x unable to find map file +23ms
  0x tidying up +12ms
```

My terminal then has an instance of `/Users/myuser/.nvm/versions/node/v4.4.4/lib/node_modules/0x/node_modules/.bin/clockface` hanging on the prompt.

A `profile-${number}` folder is created with a `.stacks.${number}.out` file within, however I can't generate a flamegraph from this, receiving the following errors on separate projects
```
(function (exports, require, module, __filename, __dirname) { node 8169 494393: profile-1ms:
                                                                   ^^^^

SyntaxError: Unexpected number
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

```
and

```
/Users/myuser/.nvm/versions/node/v4.4.4/lib/node_modules/0x/stack-convert.js:31
  var res = {
  ^

RangeError: Maximum call stack size exceeded
    at Node.serialize (/Users/briggc08/.nvm/versions/node/v4.4.4/lib/node_modules/0x/stack-convert.js:31:3)
    at Node.serialize (/Users/briggc08/.nvm/versions/node/v4.4.4/lib/node_modules/0x/stack-convert.js:40:38)
    at Node.serialize (/Users/briggc08/.nvm/versions/node/v4.4.4/lib/node_modules/0x/stack-convert.js:40:38)
    at Node.serialize (/Users/briggc08/.nvm/versions/node/v4.4.4/lib/node_modules/0x/stack-convert.js:40:38)
    at Node.serialize (/Users/briggc08/.nvm/versions/node/v4.4.4/lib/node_modules/0x/stack-convert.js:40:38)
    at Node.serialize (/Users/briggc08/.nvm/versions/node/v4.4.4/lib/node_modules/0x/stack-convert.js:40:38)
    at Node.serialize (/Users/briggc08/.nvm/versions/node/v4.4.4/lib/node_modules/0x/stack-convert.js:40:38)
    at Node.serialize (/Users/briggc08/.nvm/versions/node/v4.4.4/lib/node_modules/0x/stack-convert.js:40:38)
    at Node.serialize (/Users/briggc08/.nvm/versions/node/v4.4.4/lib/node_modules/0x/stack-convert.js:40:38)
    at Node.serialize (/Users/briggc08/.nvm/versions/node/v4.4.4/lib/node_modules/0x/stack-convert.js:40:38)
```

I'm happy to provide additional information that may be useful.

**Comment by davidmarkclements** [comment]
interesting, I wonder if nvm has something to do with this

When you run the process you should have a file in /tmp named perf.$PID$.map where $PID$ is the pid of proc. 

Can we check that the perf map file is in the tmp folder?

**Comment by Limess** [comment]
That file does exist in `/tmp`:
`$ ls -la /tmp/`
 `-rw-r--r--  1 myuser  mygroup  2292759 Jun  8 09:24 perf-15808.map`

**Comment by davidmarkclements** [comment]
@Limess does this happen with a particular piece of code, or is it happening regardless of what you attempt to profile? If a particular piece of code, can I get that code from so I can try to reproduce?

**Comment by Limess** [comment]
@davidmarkclements I've just tested this with a very simple piece of sample code and obtained a working flamegraph.

Unfortunately the particular piece of code is a large express server application which I can't expose... Obviously this isn't ideal - is there anything that comes to mind which I could do to easily isolate the problem without sharing this directly?

**Comment by davidmarkclements** [comment]
When 0x runs your server, it passes an `-r` flag pointing to https://github.com/davidmarkclements/0x/blob/master/soft-exit.js so that a SIGINT handler attaches to the process, and calls process.exit on SIGINT. If this doesn't happen, perf map generation fails because the process doesn't quit gracefully. 

It's possible that the server is doing something to override/clash with this, or it may be that something is attempting to keep the process open regardless

try including the soft exit code in your process manually, possibly modify it so it does a server.close() and any other relevant tidy up that's specific to your code

include the exit code before anything else, if that doesn't work, try including after everything else instead

if it still doesn't work, remove deps one at a time from your entry point (... app.js ?), until you can get a flamegraph, then figure out why that module is preventing perf map generation

**Comment by Limess** [comment]
So I managed to get a flamegraph output after removing the `-r` hook altogether and handling the shutdown in the application code. I couldn't simply catch `exit` or `SIGTERM` events as the `soft-exit` hook caught them first and issued a `process.exit` which prevents async handlers (i.e `app.close`).

Not sure of the best way to continue with this, flag whether to handle `SIGTERM` manually? Debug if there's something in my specific application causing a non-graceful exit.

**Comment by craigkj** [comment]
Same issue described in a little more detail here: https://github.com/davidmarkclements/0x/issues/33

**Comment by davidmarkclements** [comment]
covered by #35
