### ISSUE TITLE
"Cannot find module 'browserify-string'" when generating flamegraph

### ISSUE THREAD

**Issue by NicolaOrritos** [davidmarkclements/0x#39]
When trying to generate a flamegraph from a previously created stacks.\<PID\>.out I get the following error (0x version is 2.2.8, installed via NPM):

```Bash
$ 0x -c gen stacks.14499.out 
module.js:442
    throw err;
    ^

Error: Cannot find module 'browserify-string'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/0x/command.js:3:12)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

Here's the output of the npm install:
```Bash
$ sudo npm install -g 0x
/usr/bin/0x -> /usr/lib/node_modules/0x/cmd.js
/usr/lib
└─┬ 0x@2.2.8 
  ├─┬ browserify@13.1.0 
  │ ├── assert@1.3.0 
  │ ├─┬ browser-pack@6.0.1 
  │ │ ├─┬ combine-source-map@0.7.2 
  │ │ │ ├── convert-source-map@1.1.3 
  │ │ │ ├── inline-source-map@0.6.2 
  │ │ │ ├── lodash.memoize@3.0.4 
  │ │ │ └── source-map@0.5.6 
  │ │ └── umd@3.0.1 
  │ ├── browser-resolve@1.11.2 
  │ ├─┬ browserify-zlib@0.1.4 
  │ │ └── pako@0.2.9 
  │ ├─┬ buffer@4.9.1 
  │ │ ├── base64-js@1.1.2 
  │ │ ├── ieee754@1.1.6 
  │ │ └── isarray@1.0.0 
  │ ├─┬ concat-stream@1.5.1 
  │ │ ├── readable-stream@2.0.6 
  │ │ └── typedarray@0.0.6 
  │ ├─┬ console-browserify@1.1.0 
  │ │ └── date-now@0.1.4 
  │ ├── constants-browserify@1.0.0 
  │ ├─┬ crypto-browserify@3.11.0 
  │ │ ├─┬ browserify-cipher@1.0.0 
  │ │ │ ├─┬ browserify-aes@1.0.6 
  │ │ │ │ └── buffer-xor@1.0.3 
  │ │ │ ├─┬ browserify-des@1.0.0 
  │ │ │ │ └─┬ des.js@1.0.0 
  │ │ │ │   └── minimalistic-assert@1.0.0 
  │ │ │ └── evp_bytestokey@1.0.0 
  │ │ ├─┬ browserify-sign@4.0.0 
  │ │ │ ├── bn.js@4.11.6 
  │ │ │ ├── browserify-rsa@4.0.1 
  │ │ │ ├─┬ elliptic@6.3.1 
  │ │ │ │ ├── brorand@1.0.5 
  │ │ │ │ └── hash.js@1.0.3 
  │ │ │ └─┬ parse-asn1@5.0.0 
  │ │ │   └── asn1.js@4.8.0 
  │ │ ├── create-ecdh@4.0.0 
  │ │ ├─┬ create-hash@1.1.2 
  │ │ │ ├── cipher-base@1.0.2 
  │ │ │ └── ripemd160@1.0.1 
  │ │ ├── create-hmac@1.1.4 
  │ │ ├─┬ diffie-hellman@5.0.2 
  │ │ │ └── miller-rabin@4.0.0 
  │ │ ├── pbkdf2@3.0.4 
  │ │ ├── public-encrypt@4.0.0 
  │ │ └── randombytes@2.0.3 
  │ ├── defined@1.0.0 
  │ ├── deps-sort@2.0.0 
  │ ├── domain-browser@1.1.7 
  │ ├── duplexer2@0.1.4 
  │ ├── events@1.1.1 
  │ ├─┬ glob@5.0.15 
  │ │ ├── inflight@1.0.5 
  │ │ ├─┬ minimatch@3.0.3 
  │ │ │ └─┬ brace-expansion@1.1.6 
  │ │ │   ├── balanced-match@0.4.2 
  │ │ │   └── concat-map@0.0.1 
  │ │ └── path-is-absolute@1.0.0 
  │ ├─┬ has@1.0.1 
  │ │ └── function-bind@1.1.0 
  │ ├── htmlescape@1.1.1 
  │ ├── https-browserify@0.0.1 
  │ ├── inherits@2.0.1 
  │ ├─┬ insert-module-globals@7.0.1 
  │ │ ├── is-buffer@1.1.4 
  │ │ └─┬ lexical-scope@1.2.0 
  │ │   └── astw@2.0.0 
  │ ├─┬ JSONStream@1.1.4 
  │ │ └── jsonparse@1.2.0 
  │ ├─┬ labeled-stream-splicer@2.0.0 
  │ │ ├── isarray@0.0.1 
  │ │ └── stream-splicer@2.0.0 
  │ ├─┬ module-deps@4.0.7 
  │ │ ├─┬ detective@4.3.1 
  │ │ │ └── acorn@1.2.2 
  │ │ └── stream-combiner2@1.1.1 
  │ ├── os-browserify@0.1.2 
  │ ├─┬ parents@1.0.1 
  │ │ └── path-platform@0.11.15 
  │ ├── path-browserify@0.0.0 
  │ ├── process@0.11.8 
  │ ├── punycode@1.4.1 
  │ ├── querystring-es3@0.2.1 
  │ ├── read-only-stream@2.0.0 
  │ ├─┬ readable-stream@2.1.5 
  │ │ ├── buffer-shims@1.0.0 
  │ │ ├── core-util-is@1.0.2 
  │ │ ├── process-nextick-args@1.0.7 
  │ │ └── util-deprecate@1.0.2 
  │ ├── resolve@1.1.7 
  │ ├─┬ shasum@1.0.2 
  │ │ ├── json-stable-stringify@0.0.1 
  │ │ └── sha.js@2.4.5 
  │ ├─┬ shell-quote@1.6.1 
  │ │ ├── array-filter@0.0.1 
  │ │ ├── array-map@0.0.0 
  │ │ ├── array-reduce@0.0.0 
  │ │ └── jsonify@0.0.0 
  │ ├── stream-browserify@2.0.1 
  │ ├─┬ stream-http@2.3.1 
  │ │ ├── builtin-status-codes@2.0.0 
  │ │ └── to-arraybuffer@1.0.1 
  │ ├── string_decoder@0.10.31 
  │ ├── subarg@1.0.0 
  │ ├─┬ syntax-error@1.1.6 
  │ │ └── acorn@2.7.0 
  │ ├── timers-browserify@1.4.2 
  │ ├── tty-browserify@0.0.0 
  │ ├─┬ url@0.11.0 
  │ │ ├── punycode@1.3.2 
  │ │ └── querystring@0.2.0 
  │ ├── util@0.10.3 
  │ ├─┬ vm-browserify@0.0.4 
  │ │ └── indexof@0.0.1 
  │ └── xtend@4.0.1 
  ├─┬ clean-browserify-string@1.0.0 
  │ └── through@2.3.8 
  ├─┬ clockface@1.1.1 
  │ └── ansi-escapes@1.4.0 
  ├── d3@3.5.17 
  ├─┬ debug@2.2.0 
  │ └── ms@0.7.1 
  ├─┬ end-of-stream@1.1.0 
  │ └─┬ once@1.3.3 
  │   └── wrappy@1.0.2 
  ├── hsl-to-rgb-for-reals@1.1.0 
  ├─┬ jsdom@8.5.0 
  │ ├── abab@1.0.3 
  │ ├── acorn@2.7.0 
  │ ├─┬ acorn-globals@1.0.9 
  │ │ └── acorn@2.7.0 
  │ ├── array-equal@1.0.0 
  │ ├── cssom@0.3.1 
  │ ├── cssstyle@0.2.37 
  │ ├─┬ escodegen@1.8.1 
  │ │ ├── esprima@2.7.3 
  │ │ ├── estraverse@1.9.3 
  │ │ ├── esutils@2.0.2 
  │ │ ├─┬ optionator@0.8.1 
  │ │ │ ├── deep-is@0.1.3 
  │ │ │ ├── fast-levenshtein@1.1.4 
  │ │ │ ├── levn@0.3.0 
  │ │ │ ├── prelude-ls@1.1.2 
  │ │ │ ├── type-check@0.3.2 
  │ │ │ └── wordwrap@1.0.0 
  │ │ └─┬ source-map@0.2.0 
  │ │   └── amdefine@1.0.0 
  │ ├── iconv-lite@0.4.13 
  │ ├── nwmatcher@1.3.8 
  │ ├── parse5@1.5.1 
  │ ├─┬ request@2.74.0 
  │ │ ├── aws-sign2@0.6.0 
  │ │ ├── aws4@1.4.1 
  │ │ ├─┬ bl@1.1.2 
  │ │ │ └── readable-stream@2.0.6 
  │ │ ├── caseless@0.11.0 
  │ │ ├─┬ combined-stream@1.0.5 
  │ │ │ └── delayed-stream@1.0.0 
  │ │ ├── extend@3.0.0 
  │ │ ├── forever-agent@0.6.1 
  │ │ ├─┬ form-data@1.0.1 
  │ │ │ └─┬ async@2.0.1 
  │ │ │   └── lodash@4.15.0 
  │ │ ├─┬ har-validator@2.0.6 
  │ │ │ ├─┬ chalk@1.1.3 
  │ │ │ │ ├── ansi-styles@2.2.1 
  │ │ │ │ ├── escape-string-regexp@1.0.5 
  │ │ │ │ ├── has-ansi@2.0.0 
  │ │ │ │ └── supports-color@2.0.0 
  │ │ │ ├─┬ commander@2.9.0 
  │ │ │ │ └── graceful-readlink@1.0.1 
  │ │ │ ├─┬ is-my-json-valid@2.13.1 
  │ │ │ │ ├── generate-function@2.0.0 
  │ │ │ │ ├─┬ generate-object-property@1.2.0 
  │ │ │ │ │ └── is-property@1.0.2 
  │ │ │ │ └── jsonpointer@2.0.0 
  │ │ │ └─┬ pinkie-promise@2.0.1 
  │ │ │   └── pinkie@2.0.4 
  │ │ ├─┬ hawk@3.1.3 
  │ │ │ ├── boom@2.10.1 
  │ │ │ ├── cryptiles@2.0.5 
  │ │ │ ├── hoek@2.16.3 
  │ │ │ └── sntp@1.0.9 
  │ │ ├─┬ http-signature@1.1.1 
  │ │ │ ├── assert-plus@0.2.0 
  │ │ │ ├─┬ jsprim@1.3.0 
  │ │ │ │ ├── extsprintf@1.0.2 
  │ │ │ │ ├── json-schema@0.2.2 
  │ │ │ │ └── verror@1.3.6 
  │ │ │ └─┬ sshpk@1.10.0 
  │ │ │   ├── asn1@0.2.3 
  │ │ │   ├── assert-plus@1.0.0 
  │ │ │   ├─┬ bcrypt-pbkdf@1.0.0 
  │ │ │   │ └── tweetnacl@0.14.3 
  │ │ │   ├─┬ dashdash@1.14.0 
  │ │ │   │ └── assert-plus@1.0.0 
  │ │ │   ├── ecc-jsbn@0.1.1 
  │ │ │   ├─┬ getpass@0.1.6 
  │ │ │   │ └── assert-plus@1.0.0 
  │ │ │   ├── jodid25519@1.0.2 
  │ │ │   ├── jsbn@0.1.0 
  │ │ │   └── tweetnacl@0.13.3 
  │ │ ├── is-typedarray@1.0.0 
  │ │ ├── isstream@0.1.2 
  │ │ ├── json-stringify-safe@5.0.1 
  │ │ ├─┬ mime-types@2.1.11 
  │ │ │ └── mime-db@1.23.0 
  │ │ ├── node-uuid@1.4.7 
  │ │ ├── oauth-sign@0.8.2 
  │ │ ├── qs@6.2.1 
  │ │ ├── stringstream@0.0.5 
  │ │ └── tunnel-agent@0.4.3 
  │ ├── sax@1.2.1 
  │ ├── symbol-tree@3.1.4 
  │ ├── tough-cookie@2.3.1 
  │ ├── webidl-conversions@3.0.1 
  │ ├─┬ whatwg-url@2.0.1 
  │ │ └── tr46@0.0.3 
  │ └── xml-name-validator@2.0.1 
  ├── minimist@1.2.0 
  ├─┬ perf-sym@2.0.0 
  │ └─┬ resolve-jit-symbols@0.5.0 
  │   └─┬ pretty-trace@0.3.1 
  │     ├── ansicolors@0.2.1 
  │     └─┬ split2@0.2.1 
  │       └─┬ through2@0.6.5 
  │         └─┬ readable-stream@1.0.34 
  │           └── isarray@0.0.1 
  ├── pump@1.0.1 
  ├─┬ single-line-log@1.1.1 
  │ └─┬ string-width@1.0.2 
  │   ├─┬ code-point-at@1.0.0 
  │   │ └── number-is-nan@1.0.0 
  │   ├── is-fullwidth-code-point@1.0.0 
  │   └─┬ strip-ansi@3.0.1 
  │     └── ansi-regex@2.0.0 
  ├── split2@2.1.0 
  ├─┬ through2@2.0.1 
  │ └── readable-stream@2.0.6 
  └─┬ which@1.2.10 
    └── isexe@1.1.2
```

**Comment by davidmarkclements** [comment]
thanks for reporting this @NicolaOrritos - it's now fixed in v2.2.10
