### ISSUE TITLE
Huge json object resulting in RangeError: Invalid string length

### ISSUE THREAD

**Issue by alessioalex** [davidmarkclements/0x#71]
Talking about this line: https://github.com/davidmarkclements/0x/blob/master/index.js#L388

Related to: https://github.com/nodejs/node/issues/10738#issuecomment-271969191

```
/home/alessio/.nvm/versions/node/v6.9.4/lib/node_modules/0x/index.js:390
      fs.writeFileSync(folder + '/stacks.' + pid + '.json', JSON.stringify(json, 0, 2))
                                                                 ^

RangeError: Invalid string length
    at join (native)
    at Object.stringify (native)
    at write (/home/alessio/.nvm/versions/node/v6.9.4/lib/node_modules/0x/index.js:390:66)
    at /home/alessio/.nvm/versions/node/v6.9.4/lib/node_modules/0x/index.js:370:7
    at ConcatStream.<anonymous> (/home/alessio/.nvm/versions/node/v6.9.4/lib/node_modules/0x/node_modules/concat-stream/index.js:36:43)
    at emitNone (events.js:91:20)
    at ConcatStream.emit (events.js:185:7)
    at finishMaybe (/home/alessio/.nvm/versions/node/v6.9.4/lib/node_modules/0x/node_modules/readable-stream/lib/_stream_writable.js:503:14)
    at endWritable (/home/alessio/.nvm/versions/node/v6.9.4/lib/node_modules/0x/node_modules/readable-stream/lib/_stream_writable.js:513:3)
    at ConcatStream.Writable.end (/home/alessio/.nvm/versions/node/v6.9.4/lib/node_modules/0x/node_modules/readable-stream/lib/_stream_writable.js:483:41)
```

I suggest using replacing `fs.writeFileSync()` with a JSON stream of sorts.

**Comment by davidmarkclements** [comment]
yes I've come across this, converting to streams is on the todo list

**Comment by alessioalex** [comment]
If you need some help and have a rough idea on what to do let me know. I could help out.

**Comment by davidmarkclements** [comment]
I'm going to get some focus on 0x soon - I'll come back to you on that :bowtie:

**Comment by davidmarkclements** [comment]
ok so I've remembered *why* we don't use streams

well, actually we do use streams, up to a point - which is where we have to build the tree

at this point there's not much point in trying to incrementally build the tree - because if node runs out of memory here, then the browser will as well - and they both have to handle the same tree 

however, we *could* change to a sort of normalized tree - a flat structure with parent references instead of a nested structure - this might solve the stringification problem, but may also lead to a bigger performance issue in the browser

**Comment by s9tpepper** [comment]
Are there any current workarounds to this?

**Comment by davidmarkclements** [comment]
try https://github.com/davidmarkclements/0x#memory-issues

you could also try `--max-old-space-size=8000` - I *think* the max string length is calculated based on max old space

**Comment by davidmarkclements** [comment]
I think this is less of a problem with larger JSON string size on 64bit system with newer version of turbofan
